CREATE SCHEMA IF NOT EXISTS reward;

ALTER TABLE IF EXISTS public.milestone_spend_based_reward SET SCHEMA reward;
ALTER TABLE IF EXISTS public.milestone_spend_based_reward_distance SET SCHEMA reward;

CREATE TABLE IF NOT EXISTS reward.milestone_spend_based_reward (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id UUID NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS reward.milestone_spend_based_reward_distance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reward_id UUID NOT NULL UNIQUE,
    current_milestone JSONB,
    previous_milestone JSONB,
    next_milestone JSONB
);
