package com.credzin.merchant.domain

enum class MerchantCategoryGroup {
    AGRICULTURAL_SERVICES,
    CONTRACTED_SERVICES,
    TRANSPORTATION,
    UTILITIES_AND_TELECOM,
    RETAIL_OUTLETS,
    CLOTHING_STORES,
    MISC_RETAIL,
    BUSINESS_SERVICES,
    HEALTH_EDUCATION_MEMBERSHIP,
    GOVERNMENT_NONPROFIT,
}