ALTER TABLE IF EXISTS public.revinfo SET SCHEMA merchant;
ALTER TABLE IF EXISTS public.merchant_audit SET SCHEMA merchant;
ALTER TABLE IF EXISTS public.merchant_mcc_audit SET SCHEMA merchant;
ALTER TABLE IF EXISTS public.merchant_category_code_audit SET SCHEMA merchant;

CREATE TABLE IF NOT EXISTS merchant.revinfo (
    rev INT GENERATED BY DEFAULT AS IDENTITY,
    revtstmp BIGINT,
    PRIMARY KEY (rev)
);

CREATE TABLE IF NOT EXISTS merchant.merchant_audit (
    id UUID,
    legal_name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT NOT NULL,
    created_by VARCHAR(255) NOT NULL DEFAULT 'system_user',
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(255),
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_merchant_audit_revinfo FOREIGN KEY (rev) REFERENCES merchant.revinfo (rev)
);

CREATE TABLE IF NOT EXISTS merchant.merchant_mcc_audit (
    id UUID,
    merchant_id UUID NOT NULL,
    mcc_code INT NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT NOT NULL,
    created_by VARCHAR(255) NOT NULL DEFAULT 'system_user',
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(255),
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_merchant_mcc_audit_revinfo FOREIGN KEY (rev) REFERENCES merchant.revinfo (rev)
);

CREATE TABLE IF NOT EXISTS merchant.merchant_category_code_audit (
    id UUID,
    card_network VARCHAR(255) NOT NULL,
    code INT NOT NULL,
    description VARCHAR(255) NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT NOT NULL,
    created_by VARCHAR(255) NOT NULL DEFAULT 'system_user',
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(255),
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_merchant_category_code_audit_revinfo FOREIGN KEY (rev) REFERENCES merchant.revinfo (rev)
);
